import '../../components/sticky-banner/js/sticky-banner'
import '../../components/slider/js/slider'
import '../../components/faq/js/faq'
import '../../components/testimonials/js/testimonials'
import '../../components/popup/js/popup'

import '../../components/main-banner/scss/main-banner.scss'
import '../../components/content-banner/scss/content-banner.scss'
import '../../components/sticky-banner/scss/sticky-banner.scss'
import '../../components/slider/scss/slider.scss'
import '../../components/faq/scss/faq.scss'
import '../../components/testimonials/scss/testimonials.scss'
import '../../components/blockquotes/scss/blockquotes.scss'
import '../../components/advantages/scss/advantages.scss'
import '../../components/buttons-block/scss/buttons-block.scss'
import '../../components/content/scss/content.scss'
import '../../components/popup/scss/popup.scss'
